openapi: 3.1.0
info:
  title: Adapter Adapter API Docs API
  version: 0.1.0
tags:
- name: Docs
paths:
  /docs:
    get:
      summary: Get Swagger Documentation
      description: Secured Swagger UI documentation.
      operationId: get_swagger_documentation_docs_get
      responses:
        '200':
          description: Successful Response
          content:
            text/html:
              schema:
                type: string
      security:
      - HTTPBasic: []
      tags:
      - Docs
components:
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
    HTTPBearer:
      type: http
      scheme: bearer
