openapi: 3.1.0
info:
  title: Adapter Adapter API Imessage API
  version: 0.1.0
tags:
- name: Imessage
paths:
  /imessage/webhook:
    post:
      summary: Imessage Webhook
      operationId: imessage_webhook_imessage_webhook_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IMessageRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Imessage
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    IMessageRequest:
      properties:
        message:
          type: string
          title: Message
        apple_id:
          type: string
          title: Apple Id
      type: object
      required:
      - message
      - apple_id
      title: IMessageRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
    HTTPBearer:
      type: http
      scheme: bearer
